[tox]
envlist = py26,py27,py32,py33,py34,pypy
#,pypy3

# PyPy3-2.4.0 fails to lock the files:
#   zc/lockfile/__init__.py", line 57, in _lock_file
#    fcntl.flock(file.fileno(), _flags)
#   IOError: [Errno 35] Resource temporarily unavailable
# This could be a GC issue in zc.lockfile 1.1.0 due to all the ResourceWarnings about
# unclosed files:
#    ResourceWarning: unclosed file <_io.TextIOWrapper name='1.fs.lock' mode='a+' encoding='US-ASCII'>
# OTOH, at this writing PyPy3 is a major version behind PyPy (2.4 vs 2.5).

[testenv]
deps =
commands =
    python setup.py test -q
